# This file was generated by tslc at Wed Mar 22 17:26:15 2006

use strict;
use warnings;
use Tesla;

#line 7 "t/simple.tsl"
$OR::delay = 0.2;

#line 8 "t/simple.tsl"
my $A = Signal->new("A");

#line 8 "t/simple.tsl"
my $B = Signal->new("B");

#line 8 "t/simple.tsl"
my $C = Signal->new("C");

#line 9 "t/simple.tsl"
my $gate1 = OR->new();
$gate1->output($C);
$gate1->inputs($A,$B);

#line 9 "t/simple.tsl"
$A->add_dest($gate1);

#line 9 "t/simple.tsl"
$B->add_dest($gate1);

#line 10 "t/simple.tsl"
EventConsole->add_events( [0,2.2,6.5,12.2,15], $A, ['0','1','0','1','1'] );

#line 11 "t/simple.tsl"
EventConsole->add_events( [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15], $B, ['0','1','0','1','0','1','0','1','0','1','0','1','0','1','0','1'] );

#line 12 "t/simple.tsl"
Tesla->run(16);

#line 13 "t/simple.tsl"
print $C->name, " : ", $C->histp, "\n";

#line 13 "t/simple.tsl"
print "
";

#line 18 "t/simple.tsl"
Tesla->clear;

#line 19 "t/simple.tsl"
$NOT::delay = 1;

#line 20 "t/simple.tsl"
my $X = Signal->new("X");

#line 21 "t/simple.tsl"
my $gate2 = NOT->new();
$gate2->output($X);
$gate2->inputs($X);

#line 21 "t/simple.tsl"
$X->add_dest($gate2);

#line 22 "t/simple.tsl"
EventConsole->add_events( [0], $X, ['0'] );

#line 23 "t/simple.tsl"
Tesla->run(5);

#line 24 "t/simple.tsl"
print $X->name, " : ", $X->histp, "\n";

#line 24 "t/simple.tsl"
print "
";

0;
