# This file was generated by tslc at Thu Dec 14 20:19:39 2006

use strict;
use warnings;
use Tesla;

#line 8 "t/SR_latch.tsl"
$NOR::delay = 1.5;

#line 11 "t/SR_latch.tsl"
my $S = Signal->new("S");

#line 11 "t/SR_latch.tsl"
my $R = Signal->new("R");

#line 11 "t/SR_latch.tsl"
my $Q = Signal->new("Q");

#line 11 "t/SR_latch.tsl"
my $Qp = Signal->new("Qp");

#line 14 "t/SR_latch.tsl"
my $gate1 = NOR->new();
$gate1->output($Qp);
$gate1->inputs($S,$Q);

#line 14 "t/SR_latch.tsl"
$S->add_dest($gate1);

#line 14 "t/SR_latch.tsl"
$Q->add_dest($gate1);

#line 15 "t/SR_latch.tsl"
my $gate2 = NOR->new();
$gate2->output($Q);
$gate2->inputs($R,$Qp);

#line 15 "t/SR_latch.tsl"
$R->add_dest($gate2);

#line 15 "t/SR_latch.tsl"
$Qp->add_dest($gate2);

#line 18 "t/SR_latch.tsl"
Tesla->schedule( [0,10,20] => $S => ['0','1','0'] );

#line 19 "t/SR_latch.tsl"
Tesla->schedule( [0,30] => $R => ['0','1'] );

#line 21 "t/SR_latch.tsl"
Tesla->schedule( [0] => $Q => ['0'] );

#line 24 "t/SR_latch.tsl"
Tesla->run(50);

#line 27 "t/SR_latch.tsl"
print $Q->name, " : ", $Q->histp, "\n";

#line 27 "t/SR_latch.tsl"
print $Qp->name, " : ", $Qp->histp, "\n";

#line 27 "t/SR_latch.tsl"
print "
";

#line 30 "t/SR_latch.tsl"
Tesla->reset;

#line 32 "t/SR_latch.tsl"
Tesla->schedule( [0,80,84,88,92,96] => $S => ['0','1','0','1','0','1'] );

#line 33 "t/SR_latch.tsl"
Tesla->schedule( [0,35,39,43,47,51] => $R => ['1','0','1','0','1','0'] );

#line 34 "t/SR_latch.tsl"
Tesla->schedule( [0] => $Qp => ['1'] );

#line 36 "t/SR_latch.tsl"
Tesla->run(150);

#line 38 "t/SR_latch.tsl"
print $Q->name, " : ", $Q->histp, "\n";

#line 38 "t/SR_latch.tsl"
print $Qp->name, " : ", $Qp->histp, "\n";

#line 38 "t/SR_latch.tsl"
print "
";

#line 42 "t/SR_latch.tsl"
Tesla->clear;

#line 43 "t/SR_latch.tsl"
$NOR::delay = 1.5;

#line 45 "t/SR_latch.tsl"
my $A = Signal->new("A");

#line 45 "t/SR_latch.tsl"
my $B = Signal->new("B");

#line 45 "t/SR_latch.tsl"
my $C = Signal->new("C");

#line 45 "t/SR_latch.tsl"
my $D = Signal->new("D");

#line 47 "t/SR_latch.tsl"
sub SRLatch {
    if (@_ != 4) {
        my ($package, $filename, $line) = caller;
        die "$filename($line): error: ".
            "Component SRLatch expects 4 arguments.\n";
    }
    my ($S,$R,$Q,$Qp) = @_;

#line 48 "t/SR_latch.tsl"
my $C = Signal->new("SRLatch::C");

#line 49 "t/SR_latch.tsl"
my $gate3 = NOR->new();
$gate3->output($Qp);
$gate3->inputs($S,$Q);

#line 49 "t/SR_latch.tsl"
$S->add_dest($gate3);

#line 49 "t/SR_latch.tsl"
$Q->add_dest($gate3);

#line 50 "t/SR_latch.tsl"
my $gate4 = NOR->new();
$gate4->output($Q);
$gate4->inputs($R,$Qp);

#line 50 "t/SR_latch.tsl"
$R->add_dest($gate4);

#line 50 "t/SR_latch.tsl"
$Qp->add_dest($gate4);

#line 51 "t/SR_latch.tsl"
}

#line 53 "t/SR_latch.tsl"
SRLatch($A,$B,$C,$D);

#line 55 "t/SR_latch.tsl"
Tesla->schedule( [0] => $D => ['1'] );

#line 56 "t/SR_latch.tsl"
Tesla->schedule( [0,10,20] => $A => ['0','1','0'] );

#line 57 "t/SR_latch.tsl"
Tesla->schedule( [0,30] => $B => ['0','1'] );

#line 59 "t/SR_latch.tsl"
Tesla->run(50);

#line 61 "t/SR_latch.tsl"
print $C->name, " : ", $C->histp, "\n";

#line 61 "t/SR_latch.tsl"
print $D->name, " : ", $D->histp, "\n";

#line 61 "t/SR_latch.tsl"
print "
";

#line 63 "t/SR_latch.tsl"
Tesla->clear;

#line 64 "t/SR_latch.tsl"
$NOR::delay = 1.5;

#line 66 "t/SR_latch.tsl"
sub SRLatch2 {
    if (@_ != 4) {
        my ($package, $filename, $line) = caller;
        die "$filename($line): error: ".
            "Component SRLatch2 expects 4 arguments.\n";
    }
    my ($S,$R,$Q,$Qp) = @_;

#line 67 "t/SR_latch.tsl"
my $C = Signal->new("SRLatch2::C");

#line 68 "t/SR_latch.tsl"
my $gate5 = NOR->new();
$gate5->output($Qp);
$gate5->inputs($S,$Q);

#line 68 "t/SR_latch.tsl"
$S->add_dest($gate5);

#line 68 "t/SR_latch.tsl"
$Q->add_dest($gate5);

#line 69 "t/SR_latch.tsl"
my $gate6 = NOR->new();
$gate6->output($Q);
$gate6->inputs($R,$Qp);

#line 69 "t/SR_latch.tsl"
$R->add_dest($gate6);

#line 69 "t/SR_latch.tsl"
$Qp->add_dest($gate6);

#line 70 "t/SR_latch.tsl"
}

#line 72 "t/SR_latch.tsl"
SRLatch2($A,$B,$C,$D);

#line 74 "t/SR_latch.tsl"
Tesla->schedule( [0] => $D => ['1'] );

#line 75 "t/SR_latch.tsl"
Tesla->schedule( [0,10,20] => $A => ['0','1','0'] );

#line 76 "t/SR_latch.tsl"
Tesla->schedule( [0,30] => $B => ['0','1'] );

#line 78 "t/SR_latch.tsl"
Tesla->run(50);

#line 80 "t/SR_latch.tsl"
print $C->name, " : ", $C->histp, "\n";

#line 80 "t/SR_latch.tsl"
print $D->name, " : ", $D->histp, "\n";

#line 80 "t/SR_latch.tsl"
print "
";

0;
