# This file was generated by tslc at Fri Dec 15 13:37:22 2006

use strict;
use warnings;
use Tesla;

#line 7 "t/std.t.tsl"
use Test::More tests => 42;

#line 13 "t/std.t.tsl"
use std;

#line 22 "t/std.t.tsl"
my $X = Signal->new("X");

#line 22 "t/std.t.tsl"
my $Y = Signal->new("Y");

#line 22 "t/std.t.tsl"
my $Cout = Signal->new("Cout");

#line 22 "t/std.t.tsl"
my $Sum = Signal->new("Sum");

#line 23 "t/std.t.tsl"
HalfAdder($X,$Y,$Cout,$Sum);

#line 25 "t/std.t.tsl"
Tesla->schedule( [0,2] => $X => ['0','1'] );

#line 26 "t/std.t.tsl"
Tesla->schedule( [0,1,2,3] => $Y => ['0','1','0','1'] );

#line 27 "t/std.t.tsl"
Tesla->run(5);

#line 29 "t/std.t.tsl"
is( $Cout->histp, '0@0,1@3' );

#line 30 "t/std.t.tsl"
is( $Sum->histp, '0@0,1@1,0@3' );

#line 35 "t/std.t.tsl"
Tesla->clear;

#line 41 "t/std.t.tsl"
my $Cin = Signal->new("Cin");

#line 42 "t/std.t.tsl"
FullAdder($X,$Y,$Cin,$Cout,$Sum);

#line 44 "t/std.t.tsl"
Tesla->schedule( [0,4] => $X => ['0','1'] );

#line 45 "t/std.t.tsl"
Tesla->schedule( [0,2,4,6] => $Y => ['0','1','0','1'] );

#line 46 "t/std.t.tsl"
Tesla->schedule( [0,1,2,3,4,5,6,7] => $Cin => ['0','1','0','1','0','1','0','1'] );

#line 47 "t/std.t.tsl"
Tesla->run(8);

#line 49 "t/std.t.tsl"
is( $Cout->histp, '0@0,1@3,0@4,1@5' );

#line 50 "t/std.t.tsl"
is( $Sum->histp, '0@0,1@1,0@3,1@4,0@5,1@7' );

#line 55 "t/std.t.tsl"
Tesla->clear;

#line 60 "t/std.t.tsl"
my $S = Signal->new("S");

#line 60 "t/std.t.tsl"
my $R = Signal->new("R");

#line 60 "t/std.t.tsl"
my $Q = Signal->new("Q");

#line 60 "t/std.t.tsl"
my $Qp = Signal->new("Qp");

#line 61 "t/std.t.tsl"
SRLatch($S,$R,$Q,$Qp);

#line 63 "t/std.t.tsl"
Tesla->schedule( [0,11,20] => $S => ['0','1','0'] );

#line 64 "t/std.t.tsl"
Tesla->schedule( [0,28] => $R => ['0','1'] );

#line 65 "t/std.t.tsl"
Tesla->schedule( [0] => $Q => ['0'] );

#line 66 "t/std.t.tsl"
Tesla->run(50);

#line 68 "t/std.t.tsl"
is( $Q->histp, '0@0,1@11,0@28' );

#line 69 "t/std.t.tsl"
is( $Qp->histp, '1@0,0@11,1@28' );

#line 73 "t/std.t.tsl"
Tesla->reset;

#line 74 "t/std.t.tsl"
Tesla->schedule( [0,80,81,82,83,84] => $S => ['0','1','0','1','0','1'] );

#line 75 "t/std.t.tsl"
Tesla->schedule( [0,30,31,32,33,34] => $R => ['1','0','1','0','1','0'] );

#line 76 "t/std.t.tsl"
Tesla->schedule( [0] => $Q => ['0'] );

#line 77 "t/std.t.tsl"
Tesla->run(100);

#line 79 "t/std.t.tsl"
is( $Q->histp,  '0@0,1@80' );

#line 80 "t/std.t.tsl"
is( $Qp->histp, '1@0,0@80' );

#line 92 "t/std.t.tsl"
Tesla->clear;

#line 100 "t/std.t.tsl"
my $G = Signal->new("G");

#line 100 "t/std.t.tsl"
my $D = Signal->new("D");

#line 101 "t/std.t.tsl"
DLatch($D,$G,$Q,$Qp);

#line 103 "t/std.t.tsl"
Tesla->schedule( [0,4,9] => $G => ['0','1','0'] );

#line 104 "t/std.t.tsl"
Tesla->schedule( [0,1,2,3,5,6,7,8,10] => $D => ['0','1','0','1','0','1','0','1','0'] );

#line 105 "t/std.t.tsl"
Tesla->schedule( [0] => $Q => ['0'] );

#line 106 "t/std.t.tsl"
Tesla->run(15);

#line 108 "t/std.t.tsl"
is( $Q->histp, '0@0,1@4,0@5,1@6,0@7,1@8' );

#line 109 "t/std.t.tsl"
is( $Qp->histp, '1@0,0@4,1@5,0@6,1@7,0@8' );

#line 117 "t/std.t.tsl"
Tesla->clear;

#line 124 "t/std.t.tsl"
my $Ck = Signal->new("Ck");

#line 125 "t/std.t.tsl"
my $CkN = Signal->new("CkN");

#line 126 "t/std.t.tsl"
my $gate1 = NOT->new();
$gate1->output($CkN);
$gate1->inputs($Ck);

#line 126 "t/std.t.tsl"
$Ck->add_dest($gate1);

#line 127 "t/std.t.tsl"
DFlipFlop($D,$CkN,$Q,$Qp);

#line 129 "t/std.t.tsl"
Tesla->schedule( [0,21,41,82,102,109] => $D => ['1','0','1','0','1','0'] );

#line 130 "t/std.t.tsl"
Tesla->schedule( [0,10,20,30,40,50,60,70,80,90,100,110] => $Ck => ['0','1','0','1','0','1','0','1','0','1','0','1'] );

#line 131 "t/std.t.tsl"
Tesla->schedule( [120] => $Ck => ['0'] );

#line 132 "t/std.t.tsl"
Tesla->schedule( [0] => $Q => ['0'] );

#line 133 "t/std.t.tsl"
Tesla->run(130);

#line 135 "t/std.t.tsl"
is( $Q->histp,  '0@0,1@20,0@40,1@60,0@100' );

#line 136 "t/std.t.tsl"
is( $Qp->histp, '1@0,0@20,1@40,0@60,1@100' );

#line 140 "t/std.t.tsl"
Tesla->clear;

#line 141 "t/std.t.tsl"
DFlipFlop($D,$Ck,$Q,$Qp);

#line 143 "t/std.t.tsl"
Tesla->schedule( [0,20,35,50] => $Ck => ['0','1','0','1'] );

#line 144 "t/std.t.tsl"
Tesla->schedule( [0,5,10,13,23,26,29,40,45,54,58] => $D => ['0','1','0','1','0','1','0','1','0','1','0'] );

#line 145 "t/std.t.tsl"
Tesla->schedule( [0] => $Q => ['0'] );

#line 146 "t/std.t.tsl"
Tesla->run(60);

#line 148 "t/std.t.tsl"
is( $Q->histp,  '0@0,1@20,0@50' );

#line 149 "t/std.t.tsl"
is( $Qp->histp, '1@0,0@20,1@50' );

#line 154 "t/std.t.tsl"
Tesla->clear;

#line 159 "t/std.t.tsl"
my $CLK = Signal->new("CLK");

#line 160 "t/std.t.tsl"
SRFlipFlop($S,$CLK,$R,$Q,$Qp);

#line 162 "t/std.t.tsl"
Tesla->schedule( [0,10,20,30,40,50] => $CLK => ['0','1','0','1','0','1'] );

#line 163 "t/std.t.tsl"
Tesla->schedule( [0,12,32,47] => $S => ['1','0','1','0'] );

#line 164 "t/std.t.tsl"
Tesla->schedule( [0,12,32] => $R => ['0','1','0'] );

#line 165 "t/std.t.tsl"
Tesla->schedule( [0] => $Q => ['0'] );

#line 166 "t/std.t.tsl"
Tesla->run(60);

#line 168 "t/std.t.tsl"
is( $Q->histp,  '0@0,1@10,0@30,1@50' );

#line 169 "t/std.t.tsl"
is( $Qp->histp, '1@0,0@10,1@30,0@50' );

#line 174 "t/std.t.tsl"
Tesla->clear;

#line 179 "t/std.t.tsl"
JKFlipFlop($S,$CLK,$R,$Q,$Qp);

#line 181 "t/std.t.tsl"
Tesla->schedule( [0,10,20,30,40,50] => $CLK => ['0','1','0','1','0','1'] );

#line 182 "t/std.t.tsl"
Tesla->schedule( [0,12,32,47] => $S => ['1','0','1','0'] );

#line 183 "t/std.t.tsl"
Tesla->schedule( [0,12,32] => $R => ['0','1','0'] );

#line 184 "t/std.t.tsl"
Tesla->schedule( [0] => $Q => ['0'] );

#line 185 "t/std.t.tsl"
Tesla->run(60);

#line 187 "t/std.t.tsl"
is( $Q->histp,  '0@0,1@10,0@30,1@50' );

#line 188 "t/std.t.tsl"
is( $Qp->histp, '1@0,0@10,1@30,0@50' );

#line 192 "t/std.t.tsl"
Tesla->clear;

#line 193 "t/std.t.tsl"
my $J = Signal->new("J");

#line 193 "t/std.t.tsl"
my $K = Signal->new("K");

#line 193 "t/std.t.tsl"
my $Clock = Signal->new("Clock");

#line 194 "t/std.t.tsl"
JKFlipFlop($J,$Clock,$K,$Q,$Qp);

#line 196 "t/std.t.tsl"
Tesla->schedule( [0,5,15,25,35,45,55] => $Clock => ['1','0','1','0','1','0','1'] );

#line 197 "t/std.t.tsl"
Tesla->schedule( [0,20,40] => $J => ['1','0','1'] );

#line 198 "t/std.t.tsl"
Tesla->schedule( [0,20] => $K => ['0','1'] );

#line 199 "t/std.t.tsl"
Tesla->schedule( [0] => $Q => ['0'] );

#line 200 "t/std.t.tsl"
Tesla->run(60);

#line 202 "t/std.t.tsl"
is( $Q->histp,  '0@0,1@15,0@35,1@55' );

#line 203 "t/std.t.tsl"
is( $Qp->histp, '1@0,0@15,1@35,0@55' );

#line 208 "t/std.t.tsl"
Tesla->clear;

#line 213 "t/std.t.tsl"
my $T = Signal->new("T");

#line 214 "t/std.t.tsl"
my $gate2 = NOT->new();
$gate2->output($CkN);
$gate2->inputs($Ck);

#line 214 "t/std.t.tsl"
$Ck->add_dest($gate2);

#line 215 "t/std.t.tsl"
TFlipFlop($T,$CkN,$Q,$Qp);

#line 217 "t/std.t.tsl"
Tesla->schedule( [0,10,20,30,40,50,60,70] => $Ck => ['0','1','0','1','0','1','0','1'] );

#line 218 "t/std.t.tsl"
Tesla->schedule( [80] => $Ck => ['0'] );

#line 219 "t/std.t.tsl"
Tesla->schedule( [0,25,45,65] => $T => ['0','1','0','1'] );

#line 220 "t/std.t.tsl"
Tesla->schedule( [0] => $Q => ['0'] );

#line 221 "t/std.t.tsl"
Tesla->run(100);

#line 223 "t/std.t.tsl"
is( $Q->histp,  '0@0,1@40,0@80' );

#line 224 "t/std.t.tsl"
is( $Qp->histp, '1@0,0@40,1@80' );

#line 230 "t/std.t.tsl"
Tesla->clear;

#line 232 "t/std.t.tsl"
$AND::delay = 10;

#line 233 "t/std.t.tsl"
$OR::delay = 10;

#line 234 "t/std.t.tsl"
$NOT::delay = 10;

#line 236 "t/std.t.tsl"
my $A = Signal->new("A");

#line 236 "t/std.t.tsl"
my $B = Signal->new("B");

#line 236 "t/std.t.tsl"
my $Bp = Signal->new("Bp");

#line 236 "t/std.t.tsl"
my $C = Signal->new("C");

#line 236 "t/std.t.tsl"
my $E = Signal->new("E");

#line 236 "t/std.t.tsl"
my $F = Signal->new("F");

#line 237 "t/std.t.tsl"
my $gate3 = OR->new();
$gate3->output($F);
$gate3->inputs($D,$E);

#line 237 "t/std.t.tsl"
$D->add_dest($gate3);

#line 237 "t/std.t.tsl"
$E->add_dest($gate3);

#line 238 "t/std.t.tsl"
my $gate4 = AND->new();
$gate4->output($D);
$gate4->inputs($A,$Bp);

#line 238 "t/std.t.tsl"
$A->add_dest($gate4);

#line 238 "t/std.t.tsl"
$Bp->add_dest($gate4);

#line 239 "t/std.t.tsl"
my $gate5 = NOT->new();
$gate5->output($Bp);
$gate5->inputs($B);

#line 239 "t/std.t.tsl"
$B->add_dest($gate5);

#line 240 "t/std.t.tsl"
my $gate6 = AND->new();
$gate6->output($E);
$gate6->inputs($B,$C);

#line 240 "t/std.t.tsl"
$B->add_dest($gate6);

#line 240 "t/std.t.tsl"
$C->add_dest($gate6);

#line 242 "t/std.t.tsl"
Tesla->schedule( [0] => $A => ['1'] );

#line 243 "t/std.t.tsl"
Tesla->schedule( [0] => $C => ['1'] );

#line 244 "t/std.t.tsl"
Tesla->schedule( [0,20] => $B => ['1','0'] );

#line 245 "t/std.t.tsl"
Tesla->schedule( [0] => $D => ['0'] );

#line 246 "t/std.t.tsl"
Tesla->schedule( [0] => $E => ['1'] );

#line 247 "t/std.t.tsl"
Tesla->schedule( [0] => $F => ['1'] );

#line 249 "t/std.t.tsl"
Tesla->run(65);

#line 253 "t/std.t.tsl"
is( $D->histp, '0@0,1@40' );

#line 254 "t/std.t.tsl"
is( $E->histp, '1@0,0@30' );

#line 255 "t/std.t.tsl"
is( $F->histp, '1@0,0@40,1@50' );

#line 258 "t/std.t.tsl"
Tesla->clear;

#line 260 "t/std.t.tsl"
$AND::delay = 5;

#line 261 "t/std.t.tsl"
$OR::delay = 5;

#line 262 "t/std.t.tsl"
$NOT::delay = 3;

#line 264 "t/std.t.tsl"
my $Ap = Signal->new("Ap");

#line 264 "t/std.t.tsl"
my $Dp = Signal->new("Dp");

#line 264 "t/std.t.tsl"
my $W = Signal->new("W");

#line 264 "t/std.t.tsl"
my $H = Signal->new("H");

#line 264 "t/std.t.tsl"
my $Z = Signal->new("Z");

#line 265 "t/std.t.tsl"
my $gate7 = OR->new();
$gate7->output($W);
$gate7->inputs($C,$A);

#line 265 "t/std.t.tsl"
$C->add_dest($gate7);

#line 265 "t/std.t.tsl"
$A->add_dest($gate7);

#line 266 "t/std.t.tsl"
my $gate8 = NOT->new();
$gate8->output($Ap);
$gate8->inputs($A);

#line 266 "t/std.t.tsl"
$A->add_dest($gate8);

#line 267 "t/std.t.tsl"
my $gate9 = NOT->new();
$gate9->output($Dp);
$gate9->inputs($D);

#line 267 "t/std.t.tsl"
$D->add_dest($gate9);

#line 268 "t/std.t.tsl"
my $gate10 = OR->new();
$gate10->output($H);
$gate10->inputs($Ap,$Dp);

#line 268 "t/std.t.tsl"
$Ap->add_dest($gate10);

#line 268 "t/std.t.tsl"
$Dp->add_dest($gate10);

#line 269 "t/std.t.tsl"
my $gate11 = NOT->new();
$gate11->output($Bp);
$gate11->inputs($B);

#line 269 "t/std.t.tsl"
$B->add_dest($gate11);

#line 270 "t/std.t.tsl"
my $gate12 = NOT->new();
$gate12->output($X);
$gate12->inputs($C);

#line 270 "t/std.t.tsl"
$C->add_dest($gate12);

#line 271 "t/std.t.tsl"
my $gate13 = OR->new();
$gate13->output($Y);
$gate13->inputs($Bp,$D,$X);

#line 271 "t/std.t.tsl"
$Bp->add_dest($gate13);

#line 271 "t/std.t.tsl"
$D->add_dest($gate13);

#line 271 "t/std.t.tsl"
$X->add_dest($gate13);

#line 272 "t/std.t.tsl"
my $gate14 = AND->new();
$gate14->output($Z);
$gate14->inputs($W,$H,$Y);

#line 272 "t/std.t.tsl"
$W->add_dest($gate14);

#line 272 "t/std.t.tsl"
$H->add_dest($gate14);

#line 272 "t/std.t.tsl"
$Y->add_dest($gate14);

#line 274 "t/std.t.tsl"
Tesla->schedule( [0] => $A => ['0'] );

#line 275 "t/std.t.tsl"
Tesla->schedule( [0] => $B => ['1'] );

#line 276 "t/std.t.tsl"
Tesla->schedule( [0] => $D => ['0'] );

#line 277 "t/std.t.tsl"
Tesla->schedule( [0,5] => $C => ['0','1'] );

#line 278 "t/std.t.tsl"
Tesla->schedule( [0] => $W => ['0'] );

#line 279 "t/std.t.tsl"
Tesla->schedule( [0] => $X => ['1'] );

#line 280 "t/std.t.tsl"
Tesla->schedule( [0] => $Y => ['1'] );

#line 281 "t/std.t.tsl"
Tesla->schedule( [0] => $Z => ['0'] );

#line 283 "t/std.t.tsl"
Tesla->run(22);

#line 287 "t/std.t.tsl"
is( $W->histp, '0@0,1@10' );

#line 288 "t/std.t.tsl"
is( $X->histp, '1@0,0@8' );

#line 289 "t/std.t.tsl"
is( $Y->histp, '1@0,0@13' );

#line 290 "t/std.t.tsl"
is( $Z->histp, '0@0,1@15,0@18' );

#line 296 "t/std.t.tsl"
Tesla->clear;

#line 299 "t/std.t.tsl"
use std;

#line 302 "t/std.t.tsl"
my $D_A = Signal->new("D_A");

#line 302 "t/std.t.tsl"
my $D_B = Signal->new("D_B");

#line 304 "t/std.t.tsl"
my $gate15 = XOR->new();
$gate15->output($Z);
$gate15->inputs($A,$B);

#line 304 "t/std.t.tsl"
$A->add_dest($gate15);

#line 304 "t/std.t.tsl"
$B->add_dest($gate15);

#line 305 "t/std.t.tsl"
DFlipFlop($D_A,$Clock,$A,$Ap);

#line 306 "t/std.t.tsl"
DFlipFlop($D_B,$Clock,$B,$Bp);

#line 307 "t/std.t.tsl"
my $gate16 = XOR->new();
$gate16->output($D_A);
$gate16->inputs($X,$Bp);

#line 307 "t/std.t.tsl"
$X->add_dest($gate16);

#line 307 "t/std.t.tsl"
$Bp->add_dest($gate16);

#line 308 "t/std.t.tsl"
my $gate17 = OR->new();
$gate17->output($D_B);
$gate17->inputs($A,$X);

#line 308 "t/std.t.tsl"
$A->add_dest($gate17);

#line 308 "t/std.t.tsl"
$X->add_dest($gate17);

#line 310 "t/std.t.tsl"
Tesla->schedule( [0,1.6,5.5,7.4] => $X => ['0','1','0','1'] );

#line 311 "t/std.t.tsl"
Tesla->schedule( [0,1,2,3,4,5,6,7,8,9] => $Clock => ['0','1','0','1','0','1','0','1','0','1'] );

#line 312 "t/std.t.tsl"
Tesla->schedule( [10] => $Clock => ['0'] );

#line 313 "t/std.t.tsl"
Tesla->schedule( [0] => $Z => ['0'] );

#line 315 "t/std.t.tsl"
Tesla->run(12);

#line 321 "t/std.t.tsl"
is( $A->histp, '0@0,1@1,0@3,1@5,0@7,1@9' );

#line 322 "t/std.t.tsl"
is( $B->histp, '0@0,1@3' );

#line 323 "t/std.t.tsl"
is( $Z->histp, '0@0,1@1,0@5,1@7,0@9' );

#line 329 "t/std.t.tsl"
Tesla->clear;

#line 332 "t/std.t.tsl"
my $I = Signal->new("I");

#line 332 "t/std.t.tsl"
my $Xp = Signal->new("Xp");

#line 332 "t/std.t.tsl"
my $ClockN = Signal->new("ClockN");

#line 334 "t/std.t.tsl"
my $gate18 = OR->new();
$gate18->output($Z);
$gate18->inputs($E,$F,$G);

#line 334 "t/std.t.tsl"
$E->add_dest($gate18);

#line 334 "t/std.t.tsl"
$F->add_dest($gate18);

#line 334 "t/std.t.tsl"
$G->add_dest($gate18);

#line 335 "t/std.t.tsl"
my $gate19 = AND->new();
$gate19->output($E);
$gate19->inputs($X,$Bp);

#line 335 "t/std.t.tsl"
$X->add_dest($gate19);

#line 335 "t/std.t.tsl"
$Bp->add_dest($gate19);

#line 336 "t/std.t.tsl"
my $gate20 = AND->new();
$gate20->output($F);
$gate20->inputs($X,$A);

#line 336 "t/std.t.tsl"
$X->add_dest($gate20);

#line 336 "t/std.t.tsl"
$A->add_dest($gate20);

#line 337 "t/std.t.tsl"
my $gate21 = AND->new();
$gate21->output($G);
$gate21->inputs($Xp,$Ap,$B);

#line 337 "t/std.t.tsl"
$Xp->add_dest($gate21);

#line 337 "t/std.t.tsl"
$Ap->add_dest($gate21);

#line 337 "t/std.t.tsl"
$B->add_dest($gate21);

#line 338 "t/std.t.tsl"
my $gate22 = NOT->new();
$gate22->output($Xp);
$gate22->inputs($X);

#line 338 "t/std.t.tsl"
$X->add_dest($gate22);

#line 340 "t/std.t.tsl"
my $gate23 = AND->new();
$gate23->output($H);
$gate23->inputs($X,$B);

#line 340 "t/std.t.tsl"
$X->add_dest($gate23);

#line 340 "t/std.t.tsl"
$B->add_dest($gate23);

#line 341 "t/std.t.tsl"
my $gate24 = AND->new();
$gate24->output($I);
$gate24->inputs($X,$A);

#line 341 "t/std.t.tsl"
$X->add_dest($gate24);

#line 341 "t/std.t.tsl"
$A->add_dest($gate24);

#line 343 "t/std.t.tsl"
JKFlipFlop($H,$ClockN,$X,$A,$Ap);

#line 344 "t/std.t.tsl"
JKFlipFlop($X,$ClockN,$I,$B,$Bp);

#line 345 "t/std.t.tsl"
my $gate25 = NOT->new();
$gate25->output($ClockN);
$gate25->inputs($Clock);

#line 345 "t/std.t.tsl"
$Clock->add_dest($gate25);

#line 347 "t/std.t.tsl"
Tesla->schedule( [0,10,20,30] => $X => ['1','0','1','0'] );

#line 348 "t/std.t.tsl"
Tesla->schedule( [40] => $X => ['1'] );

#line 350 "t/std.t.tsl"
Tesla->schedule( [0] => $Clock => ['0'] );

#line 351 "t/std.t.tsl"
Tesla->schedule( [6,8,16,18,26,28,36,38,46,48] => $Clock => ['1','0','1','0','1','0','1','0','1','0'] );

#line 353 "t/std.t.tsl"
Tesla->run(50);

#line 357 "t/std.t.tsl"
is( $A->histp, '0@0,1@28,0@48' );

#line 358 "t/std.t.tsl"
is( $B->histp, '0@0,1@8,0@48' );

#line 359 "t/std.t.tsl"
is( $Z->histp, '1@0,0@8,1@10,0@20,1@28,0@30,1@40' );

#line 365 "t/std.t.tsl"
Tesla->clear;

#line 369 "t/std.t.tsl"
my $CP = Signal->new("CP");

#line 369 "t/std.t.tsl"
my $R_D = Signal->new("R_D");

#line 369 "t/std.t.tsl"
my $S_D = Signal->new("S_D");

#line 370 "t/std.t.tsl"
DFlipFlopEx($D,$CP,$S_D,$R_D,$Q,$Qp);

#line 372 "t/std.t.tsl"
Tesla->schedule( [0,1,2,3,4,5,6,7,8,9] => $CP => ['0','1','0','1','0','1','0','1','0','1'] );

#line 373 "t/std.t.tsl"
Tesla->schedule( [10] => $CP => ['0'] );

#line 374 "t/std.t.tsl"
Tesla->schedule( [0,0.4,1.5,2.3,3.1,5.5,6.1,6.5,8.8] => $D => ['0','1','0','1','0','1','0','1','0'] );

#line 375 "t/std.t.tsl"
Tesla->schedule( [0,2,2.8,7.2,7.8] => $R_D => ['1','0','1','0','1'] );

#line 376 "t/std.t.tsl"
Tesla->schedule( [0,5.2,6.1,9.4,10.2] => $S_D => ['1','0','1','0','1'] );

#line 378 "t/std.t.tsl"
Tesla->run(10.5);

#line 382 "t/std.t.tsl"
is( $Q->histp, '0@0,1@1,0@2,1@3,0@5,1@5.2,0@7.2,1@9.4' );

#line 384 "t/std.t.tsl"
Tesla->clear;

#line 388 "t/std.t.tsl"
my $CPp = Signal->new("CPp");

#line 389 "t/std.t.tsl"
my $gate26 = NOT->new();
$gate26->output($CPp);
$gate26->inputs($CP);

#line 389 "t/std.t.tsl"
$CP->add_dest($gate26);

#line 390 "t/std.t.tsl"
DFlipFlopEx($D,$CPp,$S_D,$R_D,$Q,$Qp);

#line 392 "t/std.t.tsl"
Tesla->schedule( [0,1,2,3,4,5,6,7,8,9] => $CP => ['0','1','0','1','0','1','0','1','0','1'] );

#line 393 "t/std.t.tsl"
Tesla->schedule( [10] => $CP => ['0'] );

#line 394 "t/std.t.tsl"
Tesla->schedule( [0,0.4,1.5,2.3,3.1,5.5,6.1,6.5,8.8] => $D => ['0','1','0','1','0','1','0','1','0'] );

#line 395 "t/std.t.tsl"
Tesla->schedule( [0,2,2.8,7.2,7.8] => $R_D => ['1','0','1','0','1'] );

#line 396 "t/std.t.tsl"
Tesla->schedule( [0,5.2,6.1,9.4,10.2] => $S_D => ['1','0','1','0','1'] );

#line 398 "t/std.t.tsl"
Tesla->run(10.5);

#line 402 "t/std.t.tsl"
is( $Q->histp, '0@0,1@5.2,0@7.2,1@8' );

#line 408 "t/std.t.tsl"
Tesla->clear;

#line 412 "t/std.t.tsl"
my $gate27 = XOR->new();
$gate27->output($Z);
$gate27->inputs($X,$Q);

#line 412 "t/std.t.tsl"
$X->add_dest($gate27);

#line 412 "t/std.t.tsl"
$Q->add_dest($gate27);

#line 413 "t/std.t.tsl"
my $gate28 = NOT->new();
$gate28->output($CPp);
$gate28->inputs($CP);

#line 413 "t/std.t.tsl"
$CP->add_dest($gate28);

#line 414 "t/std.t.tsl"
JKFlipFlop($Z,$CPp,$Z,$Q,$Qp);

#line 416 "t/std.t.tsl"
Tesla->schedule( [0,14,32,44,54,64] => $X => ['0','1','0','1','0','1'] );

#line 417 "t/std.t.tsl"
Tesla->schedule( [0,7,10,17,20,27,30,37,40,47,50,57,60,67] => $CP => ['0','1','0','1','0','1','0','1','0','1','0','1','0','1'] );

#line 418 "t/std.t.tsl"
Tesla->schedule( [70] => $CP => ['0'] );

#line 420 "t/std.t.tsl"
Tesla->run(75);

#line 424 "t/std.t.tsl"
is( $Q->histp, '0@0,1@20,0@40,1@50,0@60,1@70' );

#line 425 "t/std.t.tsl"
is( $Z->histp, '0@0,1@14,0@20,1@32,0@40,1@44,0@50,1@54,0@60,1@64,0@70' );

#line 431 "t/std.t.tsl"
Tesla->clear;

#line 433 "t/std.t.tsl"
my $J0 = Signal->new("J0");

#line 433 "t/std.t.tsl"
my $Y0 = Signal->new("Y0");

#line 433 "t/std.t.tsl"
my $Y0p = Signal->new("Y0p");

#line 433 "t/std.t.tsl"
my $K1 = Signal->new("K1");

#line 433 "t/std.t.tsl"
my $K1p = Signal->new("K1p");

#line 433 "t/std.t.tsl"
my $Y1 = Signal->new("Y1");

#line 433 "t/std.t.tsl"
my $Y1p = Signal->new("Y1p");

#line 434 "t/std.t.tsl"
my $gate29 = NAND->new();
$gate29->output($K1p);
$gate29->inputs($Y0,$X);

#line 434 "t/std.t.tsl"
$Y0->add_dest($gate29);

#line 434 "t/std.t.tsl"
$X->add_dest($gate29);

#line 435 "t/std.t.tsl"
my $gate30 = NOT->new();
$gate30->output($K1);
$gate30->inputs($K1p);

#line 435 "t/std.t.tsl"
$K1p->add_dest($gate30);

#line 436 "t/std.t.tsl"
my $gate31 = NOT->new();
$gate31->output($Xp);
$gate31->inputs($X);

#line 436 "t/std.t.tsl"
$X->add_dest($gate31);

#line 437 "t/std.t.tsl"
my $gate32 = NOT->new();
$gate32->output($CPp);
$gate32->inputs($CP);

#line 437 "t/std.t.tsl"
$CP->add_dest($gate32);

#line 438 "t/std.t.tsl"
JKFlipFlop($Xp,$CPp,$K1,$Y1,$Y1p);

#line 440 "t/std.t.tsl"
my $gate33 = NAND->new();
$gate33->output($Z);
$gate33->inputs($K1,$Y1);

#line 440 "t/std.t.tsl"
$K1->add_dest($gate33);

#line 440 "t/std.t.tsl"
$Y1->add_dest($gate33);

#line 442 "t/std.t.tsl"
my $gate34 = NAND->new();
$gate34->output($J0);
$gate34->inputs($Y1,$X);

#line 442 "t/std.t.tsl"
$Y1->add_dest($gate34);

#line 442 "t/std.t.tsl"
$X->add_dest($gate34);

#line 443 "t/std.t.tsl"
JKFlipFlop($J0,$CPp,$X,$Y0,$Y0p);

#line 445 "t/std.t.tsl"
Tesla->schedule( [0,13,33,43,63] => $X => ['0','1','0','1','0'] );

#line 446 "t/std.t.tsl"
Tesla->schedule( [0,7,10,17,20,27,30,37,40,47,50,57,60,67] => $CP => ['0','1','0','1','0','1','0','1','0','1','0','1','0','1'] );

#line 447 "t/std.t.tsl"
Tesla->schedule( [70] => $CP => ['0'] );

#line 449 "t/std.t.tsl"
Tesla->run(75);

#line 453 "t/std.t.tsl"
is( $Y0->histp, '0@0,1@10,0@20,1@30,0@50,1@60' );

#line 454 "t/std.t.tsl"
is( $Y1->histp, '0@0,1@10,0@20,1@40,0@50,1@70' );

#line 455 "t/std.t.tsl"
is( $Z->histp, '1@0,0@13,1@20,0@43,1@50' );

0;
