#!/usr/bin/perl -w

use strict;

my $CC = shift || 'g++';

`g++ -o 01test 01test.cpp pv.c`;

`$CC -c pv.c`;
`$CC -o init init.c pv.o`;
`$CC -o destroy destroy.c pv.o`;
`$CC -o father father.c pv.o`;
`$CC -o mother mother.c pv.o`;
`$CC -o son son.c pv.o`;
`$CC -o daughter daughter.c pv.o`;
