=head1 NAME

实验1 - 数据库的定义和建立实验

=head1 实验目的

要求学生熟练掌惶和使用 T-SQL, SQL Server 企业管理器创建数据库，基本表，视
图、索引和修改表结构，及向数据库输主数居的操作；学会创建和使用表的主外码和约
束。

=head1 实验内容

本实验针对上述两个题目分别完成以下相应任务：

=over

=item 1.

创建相应的数据库和查看数据库属性；

=item 2.

创建基本表、确定表的主码和相应的约束，为主码建索引；

=item 3.

创建、查看视图

=item 4.

创建表之间的关联

=item 5.

利用 T-SQL 和 SQL Server 企业管理器向数据库输入数据。

